spring:
  application:
    name: pedidos-ms

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:root@localhost:32771/kofood-pedidos
    username: postgres
    password: root


  jpa:
    show-sql: on
    properties:
      hibernate:
        format_sql: true


  flyway:
    driver-class-name: org.postgresql.Driver
    user: postgres
    password: root
    url: jdbc:postgresql://postgres:root@localhost:32771/kofood-pedidos

  rabbitmq:
    username: kofood
    password: kofood
    host: localhost
    port: 5672

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}


server:
  port: 0 # setup a random port