spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kofood-pedidos
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


  jpa:
    show-sql: on
    properties:
      hibernate:
        format_sql: true


  flyway:
    driver-class-name: org.postgresql.Driver
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/kofood-pedidos

  application:
    name: pedidos-ms



eureka:
  client:
    service-url:
      default-zone: http://localhost:8081/eureka

server:
  port: 0 # setup a random port